[influxdb]
# Bind address to use for the RPC service for backup and restore.
bind-address = "0.0.0.0"
bind-port = 8088

[influxdb.meta]
  # override location where the metadata/raft database is stored
  # default is {{pkg.svc_var_path}}/lib/influxdb/meta
  dir = ""
  retention-autocreate = true
  logging-enabled = true

[influxdb.data]
  # override location where the TSM storage engine stores TSM files.
  # The default is {{pkg.svc_data_path}}/tsm
  dir = ""

  # override location where the TSM storage engine stores WAL files.
  # The default is {{pkg.svc_data_path}}/wal
  wal-dir = ""

  wal-fsync-delay = "0s"
  index-version = "inmem"
  trace-logging-enabled = false
  query-log-enabled = true

  # Settings for the TSM engine
  cache-max-memory-size = "1g"
  cache-snapshot-memory-size = "25m"
  cache-snapshot-write-cold-duration = "10m"
  compact-full-write-cold-duration = "4h"
  max-concurrent-compactions = 0
  max-index-log-file-size = "1m"
  max-series-per-database = 1000000
  max-values-per-tag = 100000

[influxdb.coordinator]
  write-timeout = "10s"
  max-concurrent-queries = 0
  query-timeout = "0s"
  log-queries-after = "0s"
  max-select-point = 0
  max-select-series = 0
  max-select-buckets = 0

[influxdb.retention]
  enabled = true
  check-interval = "30m"

[influxdb.shard-precreation]
  enabled = true
  check-interval = "10m"
  advance-period = "30m"

[influxdb.monitor]
  store-enabled = true
  store-database = "_internal"
  store-interval = "10s"

[influxdb.http]
  enabled = true
  bind-address = "0.0.0.0"
  bind-port = "8086"
  auth-enabled = false
  realm = "InfluxDB"
  log-enabled = true
  suppress-write-log = false
  access-log-path = ""
  write-tracing = false
  pprof-enabled = true
  debug-pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"
  https-private-key = ""
  shared-secret = ""
  max-row-limit = 0
  max-connection-limit = 0
  unix-socket-enabled = false
  bind-socket = "/var/run/influxdb.sock"
  max-body-size = 25000000
  max-concurrent-write-limit = 0
  max-enqueued-write-limit = 0
  enqueued-write-timeout = 0

[influxdb.ifql]
  enabled = true
  log-enabled = true
  bind-address = "0.0.0.0"
  bind-port = "8082"

[influxdb.logging]
  format = "auto"
  level = "info"
  suppress-logo = false

[influxdb.subscriber]
  enabled = true
  http-timeout = "30s"
  insecure-skip-verify = false
  ca-certs = ""
  write-concurrency = 40
  write-buffer-size = 1000

[influxdb.continuous_queries]
  enabled = true
  log-enabled = true
  query-stats-enabled = false
  run-interval = "1s"
